/* Preparation for the reviewed production handover. Pure formatting only:
   this module cannot send mail, approve a panel or read an address book.
   Pass approval/shipment decisions from authenticated server-side records,
   never directly from a participant request or a browser form. */
'use strict';
const {countryCode,regionForCountry}=require('../../preview/assets/shipping-policy.js');
const regional=require('./regional-copy.json');
const copy={
 nl:{subject:'Je paneel is goedgekeurd voor UWFL',shippingSubject:'Persoonlijke aanleverinstructies voor jouw UWFL-paneel',hello:'Hallo',approved:'Je paneel is goedgekeurd voor UWFL Pay It Forward. Dank je voor jouw bijdrage!',panel:'Paneel',number:'Deelnemersnummer',region:'Regio',wait:'Wacht nog met verzenden. Je ontvangt afzonderlijk de persoonlijke aanleverinstructies zodra Jakko de bestemming en verzending voor jouw paneel heeft bevestigd.',selected:'Jouw paneel is geselecteerd voor de NWFA Expo. De onderstaande aanlevering is voor jouw paneel bevestigd.',collection:'De onderstaande aanlevering voor inzameling is voor jouw paneel bevestigd. Dit is geen selectie voor de Amerikaanse Expo.',destination:'Bestemming',instructions:'Persoonlijke instructies',change:'Verandert het land waar je paneel zich bevindt, of is iets onduidelijk? Neem eerst contact op via de app voordat je verzendt.',exampleAddress:'[Voorbeeld: privéadres wordt uitsluitend in de persoonlijke mail ingevuld]',exampleInstructions:'[Voorbeeld: persoonlijk bevestigde afspraken voor verpakking en aanlevering]'},
 en:{subject:'Your panel is approved for UWFL',shippingSubject:'Personal delivery instructions for your UWFL panel',hello:'Hello',approved:'Your panel is approved for UWFL Pay It Forward. Thank you for your contribution!',panel:'Panel',number:'Participant number',region:'Region',wait:'Please wait before shipping. You will receive separate personal delivery instructions once Jakko has confirmed the destination and shipment for your panel.',selected:'Your panel has been selected for the NWFA Expo. The delivery below has been confirmed for your panel.',collection:'The delivery below has been confirmed for collection of your panel. This is not selection for the US Expo.',destination:'Destination',instructions:'Personal instructions',change:'If the country where your panel is located changes, or anything is unclear, contact us through the app before shipping.',exampleAddress:'[Example: the private address is inserted only in the personal email]',exampleInstructions:'[Example: personally confirmed packing and delivery arrangements]'},
 de:{subject:'Dein Paneel ist für UWFL freigegeben',shippingSubject:'Persönliche Lieferhinweise für dein UWFL-Paneel',hello:'Hallo',approved:'Dein Paneel ist für UWFL Pay It Forward freigegeben. Danke für deinen Beitrag!',panel:'Paneel',number:'Teilnehmernummer',region:'Region',wait:'Warte bitte noch mit dem Versand. Du erhältst gesonderte persönliche Lieferhinweise, sobald Jakko Ziel und Versand für dein Paneel bestätigt hat.',selected:'Dein Paneel wurde für die NWFA Expo ausgewählt. Die folgende Lieferung wurde für dein Paneel bestätigt.',collection:'Die folgende Anlieferung zur Sammlung wurde für dein Paneel bestätigt. Dies ist keine Auswahl für die Expo in den USA.',destination:'Ziel',instructions:'Persönliche Hinweise',change:'Ändert sich das Land, in dem dein Paneel liegt, oder ist etwas unklar? Kontaktiere uns vor dem Versand über die App.',exampleAddress:'[Beispiel: Die private Adresse wird nur in die persönliche E-Mail eingefügt]',exampleInstructions:'[Beispiel: persönlich bestätigte Verpackungs- und Liefervereinbarungen]'},
 fr:{subject:'Votre panneau est approuvé pour UWFL',shippingSubject:'Consignes personnelles de livraison de votre panneau UWFL',hello:'Bonjour',approved:'Votre panneau est approuvé pour UWFL Pay It Forward. Merci pour votre contribution !',panel:'Panneau',number:'Numéro de participant',region:'Région',wait:'Attendez encore avant d’expédier. Vous recevrez séparément les consignes personnelles lorsque Jakko aura confirmé la destination et l’envoi de votre panneau.',selected:'Votre panneau a été sélectionné pour la NWFA Expo. La livraison ci-dessous est confirmée pour votre panneau.',collection:'La livraison ci-dessous est confirmée pour la collecte de votre panneau. Il ne s’agit pas d’une sélection pour l’Expo américaine.',destination:'Destination',instructions:'Consignes personnelles',change:'Si le pays où se trouve votre panneau change ou si un point est incertain, contactez-nous via l’application avant l’expédition.',exampleAddress:'[Exemple : l’adresse privée est insérée uniquement dans l’e-mail personnel]',exampleInstructions:'[Exemple : consignes d’emballage et de livraison confirmées personnellement]'},
 es:{subject:'Tu panel está aprobado para UWFL',shippingSubject:'Instrucciones personales de entrega de tu panel UWFL',hello:'Hola',approved:'Tu panel está aprobado para UWFL Pay It Forward. ¡Gracias por tu contribución!',panel:'Panel',number:'Número de participante',region:'Región',wait:'Espera antes de enviar. Recibirás por separado las instrucciones personales cuando Jakko confirme el destino y el envío de tu panel.',selected:'Tu panel ha sido seleccionado para la NWFA Expo. La entrega siguiente está confirmada para tu panel.',collection:'La entrega siguiente está confirmada para la recogida de tu panel. Esto no es una selección para la Expo estadounidense.',destination:'Destino',instructions:'Instrucciones personales',change:'Si cambia el país donde se encuentra tu panel o tienes alguna duda, contacta mediante la app antes de enviarlo.',exampleAddress:'[Ejemplo: la dirección privada se incluye solo en el correo personal]',exampleInstructions:'[Ejemplo: acuerdos de embalaje y entrega confirmados personalmente]'},
 it:{subject:'Il tuo pannello è approvato per UWFL',shippingSubject:'Istruzioni personali di consegna del tuo pannello UWFL',hello:'Ciao',approved:'Il tuo pannello è approvato per UWFL Pay It Forward. Grazie per il tuo contributo!',panel:'Pannello',number:'Numero di partecipante',region:'Regione',wait:'Attendi ancora prima di spedire. Riceverai separatamente le istruzioni personali quando Jakko avrà confermato destinazione e spedizione del tuo pannello.',selected:'Il tuo pannello è stato selezionato per la NWFA Expo. La consegna seguente è confermata per il tuo pannello.',collection:'La consegna seguente è confermata per la raccolta del tuo pannello. Non è una selezione per l’Expo negli Stati Uniti.',destination:'Destinazione',instructions:'Istruzioni personali',change:'Se cambia il paese in cui si trova il pannello o qualcosa non è chiaro, contattaci tramite l’app prima di spedire.',exampleAddress:'[Esempio: l’indirizzo privato è inserito solo nell’e-mail personale]',exampleInstructions:'[Esempio: accordi di imballaggio e consegna confermati personalmente]'}
};
function buildApprovalMail(panel,decision={},destinations={}){
 if(panel.status!=='approved')return null;
 const lang=Object.hasOwn(copy,panel.lang)?panel.lang:'en',text=copy[lang],publicText=regional[lang];
 // An explicit current shipping origin takes precedence over where it was made.
 // A fallback may choose a status update, but never authorises an address release.
 const origin=countryCode(panel.shipping_country||panel.country_made),region=regionForCountry(origin);
 const destination=Object.hasOwn(destinations,decision.destinationId||'')?destinations[decision.destinationId]:null;
 const reviewed=Boolean(panel.id&&decision.panelId===panel.id&&decision.confirmed===true&&decision.reviewedByAdmin===true);
 const sameOrigin=Boolean(panel.shipping_country&&origin&&countryCode(decision.originCountry)===origin);
 const correctDestination=Boolean(destination&&destination.region===region&&((region==='eu'&&destination.kind==='collection')||(region==='americas'&&destination.kind==='expo'&&decision.expoSelected===true)));
 const readyToShip=Boolean(reviewed&&sameOrigin&&correctDestination&&destination.address?.trim()&&destination.instructions?.trim());
 const regionLabel=publicText[{eu:'regionEU',americas:'regionAmericas',other:'regionOther'}[region]];
 const parts=[`${text.hello} ${String(panel.name||'').trim()},`,'',text.approved,'',`${text.panel}: ${panel.artwork_name||'—'}`,`${text.number}: ${panel.participant_number||'—'}`,`${text.region}: ${regionLabel}`,'',publicText[region+'Text'],''];
 if(readyToShip)parts.push(region==='americas'?text.selected:text.collection,'',`${text.destination}: ${destination.name||regionLabel}`,destination.address,'',text.instructions+':',destination.instructions,'',text.change);
 else parts.push(text.wait,'',publicText.approvalSeparate);
 parts.push('',publicText.openEnd,'','UWFL Pay It Forward','https://app.unitedwoodfloorlayers.com/#contact');
 return {subject:readyToShip?text.shippingSubject:text.subject,text:parts.join('\n'),lang,region,origin,readyToShip};
}
module.exports={buildApprovalMail,copy};
