/* Review preparation: pure formatting, no mail sender or database access.
   Call after a successful authenticated panel approval. Destinations come from
   private server configuration, never from the participant or public bundle. */
'use strict';
const {countryCode,regionForCountry}=require('../../preview/assets/shipping-policy.js');
const regional=require('./regional-copy.json');
const copy={
 nl:{subject:'Je paneel is goedgekeurd voor UWFL',shippingSubject:'Je UWFL-paneel is goedgekeurd — jouw verzendgegevens',hello:'Hallo',approved:'Je paneel is goedgekeurd voor UWFL Pay It Forward. Dank je voor jouw bijdrage! Deze mail ontvang je automatisch bij de goedkeuring.',panel:'Paneel',number:'Deelnemersnummer',region:'Regio',wait:'De verzendgegevens voor jouw land zijn nog niet beschikbaar. Je paneel is wel goedgekeurd. Wacht met verzenden; we laten je weten zodra de aanleverroute is geregeld.',selected:'Jouw paneel is ook geselecteerd voor de NWFA Expo.',collection:'Voor jouw paneel gelden de onderstaande aanleverinstructies. Volg ze bij het verpakken en versturen.',destination:'Bestemming',instructions:'Aanleverinstructies',change:'Verandert het land waar je paneel zich bevindt, of is iets onduidelijk? Neem eerst contact op via de app voordat je verzendt.',exampleAddress:'[Voorbeeld: hier staat in de persoonlijke mail het privéverzendadres voor jouw regio]',exampleInstructions:'[Voorbeeld: hier staan de verpakkingsinstructies, contactgegevens en aanleverafspraken voor jouw regio]'},
 en:{subject:'Your panel is approved for UWFL',shippingSubject:'Your UWFL panel is approved — your shipping details',hello:'Hello',approved:'Your panel is approved for UWFL Pay It Forward. Thank you for your contribution! This email is sent automatically when your panel is approved.',panel:'Panel',number:'Participant number',region:'Region',wait:'Shipping details for your country are not available yet. Your panel is approved. Please wait before shipping; we will let you know when a delivery route is arranged.',selected:'Your panel has also been selected for the NWFA Expo.',collection:'The delivery instructions below apply to your panel. Follow them when packing and shipping.',destination:'Destination',instructions:'Delivery instructions',change:'If the country where your panel is located changes, or anything is unclear, contact us through the app before shipping.',exampleAddress:'[Example: the personal email contains the private shipping address for your region here]',exampleInstructions:'[Example: the packing instructions, contact details and delivery arrangements for your region appear here]'},
 de:{subject:'Dein Paneel ist für UWFL freigegeben',shippingSubject:'Dein UWFL-Paneel ist freigegeben — deine Versandangaben',hello:'Hallo',approved:'Dein Paneel ist für UWFL Pay It Forward freigegeben. Danke für deinen Beitrag! Diese E-Mail wird bei der Freigabe automatisch verschickt.',panel:'Paneel',number:'Teilnehmernummer',region:'Region',wait:'Für dein Land liegen noch keine Versandangaben vor. Dein Paneel ist freigegeben. Warte bitte mit dem Versand; wir melden uns, sobald ein Lieferweg vereinbart ist.',selected:'Dein Paneel wurde auch für die NWFA Expo ausgewählt.',collection:'Für dein Paneel gelten die folgenden Lieferhinweise. Beachte sie beim Verpacken und Versenden.',destination:'Ziel',instructions:'Lieferhinweise',change:'Ändert sich das Land, in dem dein Paneel liegt, oder ist etwas unklar? Kontaktiere uns vor dem Versand über die App.',exampleAddress:'[Beispiel: Hier steht in der persönlichen E-Mail die private Versandadresse für deine Region]',exampleInstructions:'[Beispiel: Hier stehen Verpackungshinweise, Kontaktdaten und Liefervereinbarungen für deine Region]'},
 fr:{subject:'Votre panneau est approuvé pour UWFL',shippingSubject:'Votre panneau UWFL est approuvé — vos consignes d’expédition',hello:'Bonjour',approved:'Votre panneau est approuvé pour UWFL Pay It Forward. Merci pour votre contribution ! Cet e-mail est envoyé automatiquement lors de la validation.',panel:'Panneau',number:'Numéro de participant',region:'Région',wait:'Les coordonnées d’expédition pour votre pays ne sont pas encore disponibles. Votre panneau est bien validé. Attendez avant d’expédier ; nous vous informerons dès qu’un acheminement sera prévu.',selected:'Votre panneau a également été sélectionné pour la NWFA Expo.',collection:'Les consignes ci-dessous s’appliquent à votre panneau. Suivez-les pour l’emballage et l’expédition.',destination:'Destination',instructions:'Consignes de livraison',change:'Si le pays où se trouve votre panneau change ou si un point est incertain, contactez-nous via l’application avant l’expédition.',exampleAddress:'[Exemple : l’adresse privée d’expédition pour votre région figure ici dans l’e-mail personnel]',exampleInstructions:'[Exemple : les consignes d’emballage, les coordonnées et les modalités de livraison pour votre région figurent ici]'},
 es:{subject:'Tu panel está aprobado para UWFL',shippingSubject:'Tu panel UWFL está aprobado — tus datos de envío',hello:'Hola',approved:'Tu panel está aprobado para UWFL Pay It Forward. ¡Gracias por tu contribución! Este correo se envía automáticamente al aprobar el panel.',panel:'Panel',number:'Número de participante',region:'Región',wait:'Los datos de envío para tu país aún no están disponibles. Tu panel está aprobado. Espera antes de enviarlo; te avisaremos cuando se acuerde una ruta de entrega.',selected:'Tu panel también ha sido seleccionado para la NWFA Expo.',collection:'Las instrucciones siguientes corresponden a tu panel. Síguelas al embalarlo y enviarlo.',destination:'Destino',instructions:'Instrucciones de entrega',change:'Si cambia el país donde se encuentra tu panel o tienes alguna duda, contacta mediante la app antes de enviarlo.',exampleAddress:'[Ejemplo: aquí aparece la dirección privada de envío para tu región en el correo personal]',exampleInstructions:'[Ejemplo: aquí aparecen las instrucciones de embalaje, los datos de contacto y los acuerdos de entrega para tu región]'},
 it:{subject:'Il tuo pannello è approvato per UWFL',shippingSubject:'Il tuo pannello UWFL è approvato — i tuoi dati di spedizione',hello:'Ciao',approved:'Il tuo pannello è approvato per UWFL Pay It Forward. Grazie per il tuo contributo! Questa e-mail viene inviata automaticamente all’approvazione.',panel:'Pannello',number:'Numero di partecipante',region:'Regione',wait:'I dati di spedizione per il tuo paese non sono ancora disponibili. Il pannello è approvato. Attendi prima di spedire; ti informeremo appena sarà concordato un percorso di consegna.',selected:'Il tuo pannello è stato anche selezionato per la NWFA Expo.',collection:'Per il tuo pannello valgono le istruzioni seguenti. Seguile per l’imballaggio e la spedizione.',destination:'Destinazione',instructions:'Istruzioni di consegna',change:'Se cambia il paese in cui si trova il pannello o qualcosa non è chiaro, contattaci tramite l’app prima di spedire.',exampleAddress:'[Esempio: qui compare l’indirizzo privato di spedizione per la tua regione nell’e-mail personale]',exampleInstructions:'[Esempio: qui compaiono le istruzioni di imballaggio, i contatti e gli accordi di consegna per la tua regione]'}
};
function buildApprovalMail(panel,destinations={}){
 if(panel.status!=='approved')return null;
 const lang=Object.hasOwn(copy,panel.lang)?panel.lang:'en',text=copy[lang],publicText=regional[lang];
 // New submissions provide the actual shipping country; legacy records retain
 // the existing country_made fallback. Nationality never selects a destination.
 const origin=countryCode(panel.shipping_country||panel.country_made),region=regionForCountry(origin);
 // EU/Americas get the configured regional destination automatically. Other
 // countries need a configured country route; never assume a global default.
 const countryRoutes=destinations.countries||{};
 const destination=origin&&Object.hasOwn(countryRoutes,origin)?countryRoutes[origin]:region!=='other'&&Object.hasOwn(destinations,region)?destinations[region]:null;
 const readyToShip=Boolean(destination&&destination.region===region&&typeof destination.address==='string'&&destination.address.trim()&&typeof destination.instructions==='string'&&destination.instructions.trim());
 const regionLabel=publicText[{eu:'regionEU',americas:'regionAmericas',other:'regionOther'}[region]];
 const parts=[`${text.hello}${panel.name?' '+String(panel.name).trim():''},`,'',text.approved,'',`${text.panel}: ${panel.artwork_name||'—'}`,`${text.number}: ${panel.participant_number||'—'}`,`${text.region}: ${regionLabel}`,'',...(region==='other'&&readyToShip?[]:[publicText[region+'Text']]),''];
 if(readyToShip)parts.push(text.collection,'',`${text.destination}: ${destination.name||regionLabel}`,destination.address,'',text.instructions+':',destination.instructions,'',text.change);
 else parts.push(text.wait);
 // Expo selection changes the information in the same automatic email; it is
 // never a second shipping-approval gate and never inferred from approval.
 if(region==='americas')parts.push('',panel.expo_selected===true?text.selected:publicText.expoSelection);
 parts.push('',publicText.openEnd,'','UWFL Pay It Forward','https://app.unitedwoodfloorlayers.com/#contact');
 return {subject:readyToShip?text.shippingSubject:text.subject,text:parts.join('\n'),lang,region,origin,readyToShip};
}
module.exports={buildApprovalMail,copy};
