begin;
-- Additive only: no existing registration, panel, story or approval is changed.
alter table public.registrations add column if not exists lang text;
alter table public.registrations add column if not exists request_id uuid;
alter table public.panels add column if not exists why text;
alter table public.panels add column if not exists meaning text;
alter table public.panels add column if not exists materials text;
alter table public.panels add column if not exists shipping_country text;
alter table public.panels add column if not exists request_id uuid;
alter table public.sponsors add column if not exists request_id uuid;
alter table public.organisations add column if not exists request_id uuid;
alter table public.organisations add column if not exists category text not null default 'organisation';
create unique index if not exists registrations_request_id_key on public.registrations(request_id);
create unique index if not exists panels_request_id_key on public.panels(request_id);
create unique index if not exists sponsors_request_id_key on public.sponsors(request_id);
create unique index if not exists organisations_request_id_key on public.organisations(request_id);
create table if not exists public.uwfl_messages (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(), request_id uuid not null unique,
 name text not null, company text, email text not null, message text not null,
 context text, lang text, status text not null default 'pending'
);
alter table public.uwfl_messages enable row level security;
revoke all on public.uwfl_messages from anon, authenticated;
grant all on public.uwfl_messages to service_role;
grant usage, select on sequence public.uwfl_messages_id_seq to service_role;
create table if not exists public.uwfl_mail_log (
 id bigint generated by default as identity primary key,
 event_key text not null unique, created_at timestamptz not null default now(),
 kind text not null, record_id bigint, state text not null default 'queued',
 payload jsonb not null, updated_at timestamptz not null default now()
);
alter table public.uwfl_mail_log enable row level security;
revoke all on public.uwfl_mail_log from anon, authenticated;
grant all on public.uwfl_mail_log to service_role;
grant usage, select on sequence public.uwfl_mail_log_id_seq to service_role;
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
 values ('uwfl-review','uwfl-review',false,4194304,array['image/jpeg','image/png','image/webp'])
 on conflict (id) do nothing;
notify pgrst, 'reload schema';
commit;
